import { DemoCockpit } from "@/components/vaulx/demo-cockpit";
import { SiteFooter } from "@/components/vaulx/site-footer";
import { SiteHeader } from "@/components/vaulx/site-header";

export const metadata = {
  title: "Vaulx demo cockpit · stage runner",
  description:
    "Six buttons to drive the full nine-moment Vaulx loan lifecycle against Devnet — seed, mint, custody, disburse, repay, and default/auction.",
};

export default function AdminDemoPage() {
  return (
    <>
      <SiteHeader />

      <main className="relative">
        <section className="border-b border-[var(--rule)] py-20 md:py-28">
          <div className="mx-auto w-full max-w-[1200px] px-6 md:px-10">
            <div className="flex items-center gap-3">
              <span className="h-px w-10 bg-[var(--brand)]" />
              <span className="eyebrow">Vaulx ops · demo cockpit</span>
            </div>

            <h1
              className="mt-8 font-display font-extrabold leading-[1.02] tracking-[-0.025em] text-[var(--ink)]"
              style={{
                fontSize: "clamp(2.25rem, 5vw, 3.75rem)",
                fontVariationSettings: '"opsz" 144',
              }}
            >
              Six buttons.{" "}
              <em className="italic font-normal not-italic text-[var(--brand)]">
                Nine moments.
              </em>
            </h1>

            <p className="mt-6 max-w-[62ch] font-sans text-base leading-[1.65] text-[var(--ink-dim)] md:text-[17px]">
              Each button executes one loan-lifecycle moment against the
              Vaulx programs on Solana Devnet — from lender deposit through to
              a full default-and-auction cycle. Tx signatures link out to the
              explorer; the log below tails every request in order. Click
              through the story in roughly 60 seconds with{" "}
              <span className="font-mono text-[var(--ink)]">Accelerate time</span>{" "}
              on.
            </p>

            {/* Local-only banner — must precede the cockpit so production
                viewers see the warning BEFORE clicking the buttons. */}
            <aside className="mt-10 rounded-md border-l-4 border-l-[var(--brand)] border border-[var(--rule)] bg-[var(--bg-elev-1)] p-6">
              <div className="eyebrow text-[var(--brand)]">Local-development only</div>
              <p className="mt-3 font-sans text-sm leading-[1.65] text-[var(--ink-dim)]">
                The buttons below will <strong className="text-[var(--ink)]">fail
                on Vercel</strong> with 503 errors. The route handlers read
                local files (<span className="font-mono">scripts/dev/demo-wallets.json</span>,
                {" "}<span className="font-mono">~/.config/solana/id.json</span>) that don&rsquo;t
                exist in serverless. To run the cockpit, clone the repo, run{" "}
                <span className="font-mono">pnpm seed:usdc</span>, then{" "}
                <span className="font-mono">pnpm --filter @vaulx/web dev</span> and visit{" "}
                <span className="font-mono">localhost:3000/admin/demo</span>.
              </p>
              <p className="mt-3 font-sans text-sm leading-[1.65] text-[var(--ink-dim)]">
                For a production walkthrough that works on Vercel, see the
                {" "}<a href="/demo" className="text-[var(--brand)] underline decoration-[var(--rule-strong)] underline-offset-4 hover:decoration-[var(--brand)]">
                /demo
                </a>{" "}walkthrough instead.
              </p>
            </aside>

            <div className="mt-12">
              <DemoCockpit />
            </div>

            <aside className="mt-10 rounded-md border border-[var(--rule)] bg-[var(--bg-elev-1)] p-6">
              <div className="eyebrow text-[var(--ink-muted)]">Operator note</div>
              <p className="mt-3 font-sans text-sm leading-[1.65] text-[var(--ink-dim)]">
                Local-only. The route handlers read{" "}
                <span className="font-mono">scripts/dev/demo-wallets.json</span>{" "}
                (gitignored; generated by{" "}
                <span className="font-mono">pnpm seed:usdc</span>) and the
                operator keypair at{" "}
                <span className="font-mono">~/.config/solana/id.json</span> —
                neither exists on Vercel. Seed the wallets, run the indexer +
                web app, and point this page at them. If{" "}
                <span className="font-mono">NEXT_PUBLIC_VAULX_ADMIN_PUBKEY</span>{" "}
                is set the routes require a matching{" "}
                <span className="font-mono">vaulx-admin</span> cookie or{" "}
                <span className="font-mono">x-vaulx-admin</span> header;
                otherwise the cockpit is open for anyone with network access.
              </p>
              <p className="mt-3 font-sans text-sm leading-[1.65] text-[var(--ink-dim)]">
                Moment 06 blocks while the auction duration elapses — 4s in
                accelerated mode, 5 minutes otherwise — then closes on the
                same request. Mint TRDC (02) first, then 03 → 04 → 05 operate
                on the same loan. 06 mints its own parallel overdue loan, so
                it works in any order.
              </p>
            </aside>
          </div>
        </section>
      </main>

      <SiteFooter />
    </>
  );
}
