/**
 * Moments 2 + 3 + 4 end-to-end happy-path harness (Task 2.10).
 *
 * Exercises the full borrow path on Devnet:
 *   create_ccb_trdc (Moment 2) -> confirm_custody (Moment 3) ->
 *   disburse_from_vault (Moment 4), asserting that each moment emits the
 *   expected event into `onchain_events` via the indexer, and that the TRDC
 *   state transitions PendingCustody -> ActiveInCustody -> Active while the
 *   vault moves USDC to the borrower.
 *
 * Preconditions (otherwise exits 2 = SKIPPED):
 *   - SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) + SUPABASE_SERVICE_ROLE_KEY set.
 *     Loaded from apps/indexer/.env.local and apps/web/.env.local if present.
 *   - scripts/dev/devnet-usdc.json and scripts/dev/demo-wallets.json exist
 *     (generated by scripts/dev/seed-usdc.ts). Need at least 3 demo wallets
 *     (index 0 is the lender already used by Moment 1, index 1 is borrower,
 *     index 2 is custodian).
 *   - Payer (~/.config/solana/id.json) has at least ~0.1 SOL on Devnet.
 *   - Vault for devnet USDC is initialized AND has at least 200 USDC of
 *     liquidity so the 60 USDC disburse can actually settle. If not, the
 *     harness points the operator at scripts/dev/moment-1-e2e.ts to top up.
 *
 * Run directly:
 *   pnpm exec tsx scripts/dev/moments-2-3-4-e2e.ts
 *
 * Also wrapped as a Mocha spec at tests/moments-2-3-4-e2e.spec.ts which
 * treats exit code 2 as skip and any other non-zero as failure.
 *
 * Gotcha: Anchor 0.30.1 lowercases the first letter of #[event] names in the
 * runtime parser, so we assert event_name = 'ccbTrdcCreated',
 * 'custodyConfirmed', 'disbursed'. See apps/indexer/src/main.ts.
 */
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import crypto from "node:crypto";

import dotenv from "dotenv";
import {
  AnchorProvider,
  BN,
  Program,
  Wallet,
  type Idl,
} from "@coral-xyz/anchor";
import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  SYSVAR_INSTRUCTIONS_PUBKEY,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  getAccount,
  getOrCreateAssociatedTokenAccount,
} from "@solana/spl-token";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import loanIdlJson from "../../packages/idls/src/loan.json";
import trdcIdlJson from "../../packages/idls/src/trdc.json";
import vaultIdlJson from "../../packages/idls/src/vault.json";

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const MINT_FILE = path.join(REPO_ROOT, "scripts", "dev", "devnet-usdc.json");
const WALLETS_FILE = path.join(REPO_ROOT, "scripts", "dev", "demo-wallets.json");
const INDEXER_ENV = path.join(REPO_ROOT, "apps", "indexer", ".env.local");
const WEB_ENV = path.join(REPO_ROOT, "apps", "web", ".env.local");

const EXIT_SKIPPED = 2;
const EXIT_FAIL = 1;
const EXIT_OK = 0;

// Amounts in USDC atoms (6 decimals).
const APPRAISAL = new BN("100000000"); // 100 USDC
const LOAN_AMOUNT = new BN("60000000"); //  60 USDC (60% LTV cap)
const MIN_VAULT_LIQUIDITY = new BN("200000000"); // 200 USDC
const MIN_PAYER_LAMPORTS = 0.1 * LAMPORTS_PER_SOL;

const POLL_INTERVAL_MS = 1_000;
const POLL_TIMEOUT_MS = 30_000;

function skip(reason: string): never {
  console.log(`SKIPPED: ${reason}`);
  process.exit(EXIT_SKIPPED);
}

function fail(msg: string, err?: unknown): never {
  console.error(`FAIL: ${msg}`);
  if (err) console.error(err);
  process.exit(EXIT_FAIL);
}

function loadEnvIfPresent(file: string): void {
  if (fs.existsSync(file)) dotenv.config({ path: file, override: false });
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function randomBytes32(): Uint8Array {
  return new Uint8Array(crypto.randomBytes(32));
}

function toHex(bytes: Uint8Array | number[]): string {
  return Buffer.from(bytes).toString("hex");
}

type DemoWallet = { name: string; secretKey: number[]; pubkey: string };

type EventRow = { payload: any; event_name: string; signature: string };

async function pollForEvent(
  supabase: SupabaseClient,
  signature: string,
  eventName: string,
): Promise<EventRow> {
  const deadline = Date.now() + POLL_TIMEOUT_MS;
  while (Date.now() < deadline) {
    const { data, error } = await supabase
      .from("onchain_events")
      .select("payload, event_name, signature")
      .eq("signature", signature)
      .eq("event_name", eventName)
      .maybeSingle();
    if (error && error.code !== "PGRST116") {
      fail(`Supabase query error: ${error.message}`, error);
    }
    if (data) return data as unknown as EventRow;
    await sleep(POLL_INTERVAL_MS);
  }
  fail(
    `no onchain_events row with event_name='${eventName}' and signature=${signature} ` +
      `within ${POLL_TIMEOUT_MS}ms. Is apps/indexer running against Devnet?`,
  );
}

async function main(): Promise<void> {
  // 1. Env files.
  loadEnvIfPresent(INDEXER_ENV);
  loadEnvIfPresent(WEB_ENV);

  const supabaseUrl =
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseUrl || !supabaseKey) {
    skip(
      "missing SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) and/or SUPABASE_SERVICE_ROLE_KEY",
    );
  }

  // 2. Seed files.
  if (!fs.existsSync(MINT_FILE)) skip(`missing ${MINT_FILE}`);
  if (!fs.existsSync(WALLETS_FILE)) skip(`missing ${WALLETS_FILE}`);

  const mintPk = new PublicKey(
    (JSON.parse(fs.readFileSync(MINT_FILE, "utf8")) as { mint: string }).mint,
  );
  const wallets = JSON.parse(fs.readFileSync(WALLETS_FILE, "utf8")) as DemoWallet[];
  if (wallets.length < 3) {
    skip(
      `demo-wallets.json has ${wallets.length} entries; need >= 3 (lender, borrower, custodian). ` +
        `Re-run scripts/dev/seed-usdc.ts.`,
    );
  }
  const borrower = Keypair.fromSecretKey(new Uint8Array(wallets[1].secretKey));
  const custodian = Keypair.fromSecretKey(new Uint8Array(wallets[2].secretKey));

  // 3. Payer keypair.
  const payerPath = path.join(os.homedir(), ".config", "solana", "id.json");
  if (!fs.existsSync(payerPath)) skip(`missing payer keypair at ${payerPath}`);
  const payer = Keypair.fromSecretKey(
    new Uint8Array(JSON.parse(fs.readFileSync(payerPath, "utf8"))),
  );

  // 4. Connection + payer funding check.
  const rpc = process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";
  const connection = new Connection(rpc, "confirmed");

  const payerBal = await connection.getBalance(payer.publicKey);
  if (payerBal < MIN_PAYER_LAMPORTS) {
    skip(
      `payer ${payer.publicKey.toBase58()} has ${payerBal / LAMPORTS_PER_SOL} SOL ` +
        `(< ${MIN_PAYER_LAMPORTS / LAMPORTS_PER_SOL})`,
    );
  }

  // 5. Anchor provider + programs.
  const provider = new AnchorProvider(connection, new Wallet(payer), {
    commitment: "confirmed",
  });
  const loanIdl = loanIdlJson as unknown as Idl;
  const trdcIdl = trdcIdlJson as unknown as Idl;
  const vaultIdl = vaultIdlJson as unknown as Idl;
  const loanProgramId = new PublicKey((loanIdlJson as { address: string }).address);
  const trdcProgramId = new PublicKey((trdcIdlJson as { address: string }).address);
  const vaultProgramId = new PublicKey((vaultIdlJson as { address: string }).address);

  const loanProgram = new Program(loanIdl, provider);
  const trdcProgram = new Program(trdcIdl, provider);
  const vaultProgram = new Program(vaultIdl, provider);

  // 6. Vault precheck: must be initialized and carry enough liquidity for the
  //    60 USDC disburse (we insist on 200 USDC headroom so we don't race a
  //    concurrent loan on devnet).
  const [vaultPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), mintPk.toBuffer()],
    vaultProgramId,
  );
  const vaultAccInfo = await connection.getAccountInfo(vaultPda);
  if (!vaultAccInfo) {
    skip(
      `vault ${vaultPda.toBase58()} is not initialized. Run ` +
        `\`pnpm exec tsx scripts/dev/moment-1-e2e.ts\` first to bootstrap it ` +
        `and seed initial liquidity.`,
    );
  }
  const vaultAcc = (await (vaultProgram.account as any).vault.fetch(vaultPda)) as {
    totalAssets: BN;
  };
  if (new BN(vaultAcc.totalAssets.toString()).lt(MIN_VAULT_LIQUIDITY)) {
    skip(
      `vault total_assets=${vaultAcc.totalAssets.toString()} atoms < required ` +
        `${MIN_VAULT_LIQUIDITY.toString()}. Run moment-1-e2e.ts (or another ` +
        `lender deposit) to top the vault up before Moment 4.`,
    );
  }

  // 7. Ensure LoanConfig exists and (ideally) points at our demo custodian.
  const [loanConfigPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("loan_config")],
    loanProgramId,
  );
  const loanConfig = (await (loanProgram.account as any).loanConfig.fetchNullable(
    loanConfigPda,
  )) as { custodian: PublicKey } | null;
  if (!loanConfig) {
    console.log(
      `initializing loan_config (custodian=${custodian.publicKey.toBase58()}, civic disabled)`,
    );
    await (loanProgram.methods as any)
      .initializeLoanConfig(custodian.publicKey, PublicKey.default)
      .accounts({
        loanConfig: loanConfigPda,
        admin: payer.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
  } else {
    const currentCustodian = new PublicKey(loanConfig.custodian);
    console.log(
      `loan_config already initialized; custodian=${currentCustodian.toBase58()}`,
    );
    if (!currentCustodian.equals(custodian.publicKey)) {
      console.warn(
        `WARNING: loan_config.custodian (${currentCustodian.toBase58()}) != demo-wallets[2] ` +
          `(${custodian.publicKey.toBase58()}). Moment 3 will fail with ` +
          `UnauthorizedCustodian unless the on-chain custodian signs — set ` +
          `demo-wallets[2] to the on-chain custodian, or re-init the env.`,
      );
    }
  }

  // 8. Ensure VaultConfig exists (first-writer-wins; Civic disabled). Not
  //    strictly required for create_ccb_trdc / disburse, but harmless and we
  //    want the environment self-consistent for any follow-up deposits.
  const [vaultConfigPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault_config")],
    vaultProgramId,
  );
  const existingVaultCfg = await (vaultProgram.account as any).vaultConfig.fetchNullable(
    vaultConfigPda,
  );
  if (!existingVaultCfg) {
    await (vaultProgram.methods as any)
      .initializeVaultConfig(PublicKey.default)
      .accounts({
        vaultConfig: vaultConfigPda,
        admin: payer.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
  }

  // 9. Fund custodian + borrower with a little SOL for rent + signatures.
  //    Most of the cost is paid by `payer`, but signers still need lamports
  //    to exist as accounts. Only airdrop if they are below threshold.
  for (const kp of [borrower, custodian]) {
    const bal = await connection.getBalance(kp.publicKey);
    if (bal < 0.01 * LAMPORTS_PER_SOL) {
      try {
        const sig = await connection.requestAirdrop(
          kp.publicKey,
          0.1 * LAMPORTS_PER_SOL,
        );
        await connection.confirmTransaction(sig, "confirmed");
      } catch (e) {
        // Devnet airdrop is flaky; we only need the account to exist, which
        // transferring a few lamports from payer also accomplishes.
        console.warn(
          `airdrop to ${kp.publicKey.toBase58()} failed (${
            e instanceof Error ? e.message : String(e)
          }); continuing`,
        );
      }
    }
  }

  // 10. Supabase client (for all three polls).
  const supabase: SupabaseClient = createClient(supabaseUrl, supabaseKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  // ==========================================================================
  // Moment 2 — create_ccb_trdc
  // ==========================================================================
  const loanId = Keypair.generate().publicKey;
  const dueTs = new BN(Math.floor(Date.now() / 1000) + 30 * 86400);
  const assetHintBytes = randomBytes32();
  const [trdcPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("trdc_state"), loanId.toBuffer()],
    trdcProgramId,
  );
  console.log(
    `\n[Moment 2] create_ccb_trdc loanId=${loanId.toBase58()} trdc=${trdcPda.toBase58()}`,
  );

  // payer = borrower so trdc_state.borrower (= createCcbTrdc.payer) matches
  // the borrowerAta.authority used by the atomic confirm_custody. Borrower
  // already has SOL from the airdrop loop above.
  const sig2: string = await (loanProgram.methods as any)
    .createCcbTrdc(
      loanId,
      APPRAISAL,
      LOAN_AMOUNT,
      dueTs,
      new BN(800),
      Array.from(assetHintBytes),
    )
    .accounts({
      trdcState: trdcPda,
      trdcProgram: trdcProgramId,
      payer: borrower.publicKey,
      systemProgram: SystemProgram.programId,
      loanConfig: loanConfigPda,
      kycAttestation: SystemProgram.programId, // kyc gate disabled
      priceFeed: SystemProgram.programId, // oracle disabled
    })
    .signers([borrower])
    .rpc();
  console.log(`[Moment 2] tx: ${sig2}`);
  await connection.confirmTransaction(sig2, "confirmed");

  const row2 = await pollForEvent(supabase, sig2, "ccbTrdcCreated");
  const payload2 = row2.payload ?? {};
  const payloadLoanId = String(payload2.loan_id ?? payload2.loanId ?? "");
  if (payloadLoanId !== loanId.toBase58()) {
    fail(
      `[Moment 2] payload.loan_id=${payloadLoanId} expected ${loanId.toBase58()}`,
    );
  }
  const payloadLoanAmount = String(payload2.loan_amount ?? payload2.loanAmount);
  if (payloadLoanAmount !== LOAN_AMOUNT.toString()) {
    fail(
      `[Moment 2] payload.loan_amount=${payloadLoanAmount} expected ${LOAN_AMOUNT.toString()}`,
    );
  }
  console.log(
    `[Moment 2] OK ccbTrdcCreated loan_id=${payloadLoanId} loan_amount=${payloadLoanAmount}`,
  );

  // ==========================================================================
  // Moment 3 + 4 — atomic confirm_custody (folds disburse_from_vault in)
  //
  // Per the merge spec (§3 Area E DoD: "one transaction, both gate and
  // disburse"), confirm_custody now atomically:
  //   PendingCustody → ActiveInCustody → vault::disburse → Active
  // signed only by the custodian. The on-chain ActiveInCustody window is
  // collapsed inside the same tx; observers see status flip directly to
  // Active. Both `custodyConfirmed` and `disbursed` events appear in the
  // same tx signature.
  // ==========================================================================
  const docHashBytes = randomBytes32();
  const docHashHex = toHex(docHashBytes);

  const [loanAuthorityPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("loan_authority")],
    loanProgramId,
  );

  // vault_ata (off-curve owner) should already exist — initialize_vault creates
  // it via moment-1-e2e. Bail early with guidance if missing.
  const { getAssociatedTokenAddressSync } = await import("@solana/spl-token");
  const vaultAta = getAssociatedTokenAddressSync(mintPk, vaultPda, true);
  const vaultAtaInfo = await connection.getAccountInfo(vaultAta);
  if (!vaultAtaInfo) {
    fail(
      `vault_ata ${vaultAta.toBase58()} missing; moment-1-e2e.ts is the ` +
        `canonical place to create it. Re-run it before Moment 3+4.`,
    );
  }

  // Borrower ATA — created BEFORE confirm_custody so the atomic ix's
  // `token::authority = trdc_state.borrower` constraint passes.
  const borrowerAtaAcc = await getOrCreateAssociatedTokenAccount(
    connection,
    payer,
    mintPk,
    borrower.publicKey,
  );
  const borrowerAta = borrowerAtaAcc.address;

  const borrowerBefore = (await getAccount(connection, borrowerAta)).amount;
  const vaultAtaBefore = (await getAccount(connection, vaultAta)).amount;
  const vaultBefore = (await (vaultProgram.account as any).vault.fetch(
    vaultPda,
  )) as { totalAssets: BN };

  console.log(
    `\n[Moment 3+4] atomic confirm_custody (gate + disburse) ` +
      `trdc=${trdcPda.toBase58()} doc_hash=0x${docHashHex.slice(0, 16)}… ` +
      `amount=${LOAN_AMOUNT.toString()} borrower=${borrower.publicKey.toBase58()}`,
  );

  const sigConfirm: string = await (loanProgram.methods as any)
    .confirmCustody(Array.from(docHashBytes))
    .accounts({
      trdcState: trdcPda,
      loanConfig: loanConfigPda,
      trdcProgram: trdcProgramId,
      custodian: custodian.publicKey,
      vault: vaultPda,
      assetMint: mintPk,
      vaultAta,
      borrowerAta,
      loanAuthority: loanAuthorityPda,
      vaultProgram: vaultProgramId,
      tokenProgram: TOKEN_PROGRAM_ID,
      instructionsSysvar: SYSVAR_INSTRUCTIONS_PUBKEY,
      priceFeed: SystemProgram.programId, // oracle disabled
    })
    .signers([custodian])
    .rpc();
  console.log(`[Moment 3+4] tx: ${sigConfirm}`);
  await connection.confirmTransaction(sigConfirm, "confirmed");

  // Moment 3 — custodyConfirmed event in the atomic tx.
  const row3 = await pollForEvent(supabase, sigConfirm, "custodyConfirmed");
  const payload3 = row3.payload ?? {};
  const rawDocHash = payload3.doc_hash ?? payload3.docHash;
  const rxDocHashHex = Array.isArray(rawDocHash)
    ? toHex(rawDocHash as number[])
    : typeof rawDocHash === "string"
      ? rawDocHash.replace(/^0x/, "").toLowerCase()
      : "";
  if (rxDocHashHex !== docHashHex) {
    fail(
      `[Moment 3] payload.doc_hash=${rxDocHashHex} expected ${docHashHex}`,
    );
  }
  console.log(`[Moment 3] OK custodyConfirmed (atomic tx)`);

  // Moment 4 — disbursed event in the same atomic tx.
  const row4 = await pollForEvent(supabase, sigConfirm, "disbursed");
  const payload4 = row4.payload ?? {};
  const payloadAmount = String(payload4.amount);
  if (payloadAmount !== LOAN_AMOUNT.toString()) {
    fail(
      `[Moment 4] payload.amount=${payloadAmount} expected ${LOAN_AMOUNT.toString()}`,
    );
  }

  const borrowerAfter = (await getAccount(connection, borrowerAta)).amount;
  const vaultAtaAfter = (await getAccount(connection, vaultAta)).amount;
  const vaultAfter = (await (vaultProgram.account as any).vault.fetch(
    vaultPda,
  )) as { totalAssets: BN };

  const borrowerDelta = borrowerAfter - borrowerBefore;
  const vaultAtaDelta = vaultAtaBefore - vaultAtaAfter;
  const totalAssetsDelta = new BN(vaultBefore.totalAssets.toString()).sub(
    new BN(vaultAfter.totalAssets.toString()),
  );

  if (borrowerDelta.toString() !== LOAN_AMOUNT.toString()) {
    fail(
      `[Moment 4] borrower delta=${borrowerDelta} expected ${LOAN_AMOUNT.toString()}`,
    );
  }
  if (vaultAtaDelta.toString() !== LOAN_AMOUNT.toString()) {
    fail(
      `[Moment 4] vault_ata delta=${vaultAtaDelta} expected ${LOAN_AMOUNT.toString()}`,
    );
  }
  if (totalAssetsDelta.toString() !== LOAN_AMOUNT.toString()) {
    fail(
      `[Moment 4] vault.total_assets delta=${totalAssetsDelta.toString()} expected ` +
        `${LOAN_AMOUNT.toString()}`,
    );
  }

  const trdcFinal = (await (trdcProgram.account as any).trdcState.fetch(
    trdcPda,
  )) as { status: Record<string, unknown> };
  if (!Object.prototype.hasOwnProperty.call(trdcFinal.status, "active")) {
    fail(
      `[Moment 4] TRDC status=${JSON.stringify(trdcFinal.status)} expected active`,
    );
  }
  console.log(
    `[Moment 4] OK disbursed borrower+=${borrowerDelta.toString()} ` +
      `vault-=${vaultAtaDelta.toString()} total_assets-=${totalAssetsDelta.toString()} status=Active`,
  );

  // Final report.
  console.log(
    [
      ``,
      `==== Moments 2+3+4 summary ====`,
      `loan_id       : ${loanId.toBase58()}`,
      `trdc_state    : ${trdcPda.toBase58()}`,
      `borrower      : ${borrower.publicKey.toBase58()}`,
      `custodian     : ${custodian.publicKey.toBase58()}`,
      `vault         : ${vaultPda.toBase58()}`,
      `M2 tx (create)        : ${sig2}`,
      `M3+4 tx (atomic c+d)  : ${sigConfirm}`,
      `borrower USDC : ${borrowerBefore.toString()} -> ${borrowerAfter.toString()}`,
      `vault_ata     : ${vaultAtaBefore.toString()} -> ${vaultAtaAfter.toString()}`,
      `total_assets  : ${vaultBefore.totalAssets.toString()} -> ${vaultAfter.totalAssets.toString()}`,
      `TRDC status   : Active`,
      ``,
    ].join("\n"),
  );

  process.exit(EXIT_OK);
}

main().catch((e) => {
  console.error(e);
  process.exit(EXIT_FAIL);
});
