/**
 * Moment 1 end-to-end happy-path harness (Task 1.14).
 *
 * Exercises the full path on Devnet:
 *   init vault (if needed) -> deposit 100 USDC from demo wallet 0 ->
 *   poll Supabase `onchain_events` for the `deposited` row emitted by the
 *   indexer, confirming the on-chain -> indexer -> DB round trip.
 *
 * Preconditions (otherwise exits 2 = SKIPPED):
 *   - SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) + SUPABASE_SERVICE_ROLE_KEY set.
 *     Loaded from apps/indexer/.env.local and apps/web/.env.local if present.
 *   - scripts/dev/devnet-usdc.json and scripts/dev/demo-wallets.json exist
 *     (generated by scripts/dev/seed-usdc.ts).
 *   - Payer (~/.config/solana/id.json) has at least ~0.05 SOL on Devnet.
 *
 * Run directly:
 *   pnpm exec tsx scripts/dev/moment-1-e2e.ts
 *
 * Also wrapped as a Mocha spec at tests/moment-1-e2e.spec.ts which treats
 * exit code 2 as skip and any other non-zero as failure.
 *
 * Gotcha: Anchor 0.30.1 lowercases the first letter of #[event] names in the
 * runtime parser, so the indexer persists `event_name = 'deposited'`, not
 * `'Deposited'`. See apps/indexer/src/main.ts.
 */
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

import dotenv from "dotenv";
import {
  AnchorProvider,
  BN,
  BorshCoder,
  Program,
  Wallet,
  type Idl,
} from "@coral-xyz/anchor";
import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  createAssociatedTokenAccountInstruction,
  getAccount,
  getAssociatedTokenAddressSync,
  getOrCreateAssociatedTokenAccount,
} from "@solana/spl-token";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import vaultIdlJson from "../../packages/idls/src/vault.json";

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const MINT_FILE = path.join(REPO_ROOT, "scripts", "dev", "devnet-usdc.json");
const WALLETS_FILE = path.join(REPO_ROOT, "scripts", "dev", "demo-wallets.json");
const INDEXER_ENV = path.join(REPO_ROOT, "apps", "indexer", ".env.local");
const WEB_ENV = path.join(REPO_ROOT, "apps", "web", ".env.local");

const EXIT_SKIPPED = 2;
const EXIT_FAIL = 1;
const EXIT_OK = 0;

const DEPOSIT_AMOUNT = new BN("100000000"); // 100 USDC @ 6 decimals
const MIN_PAYER_LAMPORTS = 0.05 * LAMPORTS_PER_SOL;
const POLL_INTERVAL_MS = 1_000;
const POLL_TIMEOUT_MS = 30_000;

function skip(reason: string): never {
  console.log(`SKIPPED: ${reason}`);
  process.exit(EXIT_SKIPPED);
}

function fail(msg: string, err?: unknown): never {
  console.error(`FAIL: ${msg}`);
  if (err) console.error(err);
  process.exit(EXIT_FAIL);
}

function loadEnvIfPresent(file: string): void {
  if (fs.existsSync(file)) dotenv.config({ path: file, override: false });
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

type DemoWallet = { name: string; secretKey: number[]; pubkey: string };

async function ensureAtaForOwner(
  connection: Connection,
  payer: Keypair,
  mint: PublicKey,
  owner: PublicKey,
  allowOwnerOffCurve: boolean,
): Promise<PublicKey> {
  const ata = getAssociatedTokenAddressSync(mint, owner, allowOwnerOffCurve);
  const info = await connection.getAccountInfo(ata);
  if (info) return ata;

  // Build & send an ATA-create ix paid by `payer`. We avoid
  // getOrCreateAssociatedTokenAccount for off-curve (PDA) owners because that
  // helper historically has rough edges with off-curve addresses on some
  // versions of @solana/spl-token.
  const { sendAndConfirmTransaction, Transaction } = await import("@solana/web3.js");
  const tx = new Transaction().add(
    createAssociatedTokenAccountInstruction(
      payer.publicKey,
      ata,
      owner,
      mint,
      TOKEN_PROGRAM_ID,
      ASSOCIATED_TOKEN_PROGRAM_ID,
    ),
  );
  await sendAndConfirmTransaction(connection, tx, [payer], { commitment: "confirmed" });
  return ata;
}

async function main(): Promise<void> {
  // 1. Env files.
  loadEnvIfPresent(INDEXER_ENV);
  loadEnvIfPresent(WEB_ENV);

  const supabaseUrl =
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseUrl || !supabaseKey) {
    skip(
      "missing SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) and/or SUPABASE_SERVICE_ROLE_KEY",
    );
  }

  // 2. Seed files.
  if (!fs.existsSync(MINT_FILE)) skip(`missing ${MINT_FILE}`);
  if (!fs.existsSync(WALLETS_FILE)) skip(`missing ${WALLETS_FILE}`);

  const mintPk = new PublicKey(
    (JSON.parse(fs.readFileSync(MINT_FILE, "utf8")) as { mint: string }).mint,
  );
  const wallets = JSON.parse(fs.readFileSync(WALLETS_FILE, "utf8")) as DemoWallet[];
  if (wallets.length === 0) skip("demo-wallets.json is empty");
  const depositor = Keypair.fromSecretKey(new Uint8Array(wallets[0].secretKey));

  // 3. Payer keypair.
  const payerPath = path.join(os.homedir(), ".config", "solana", "id.json");
  if (!fs.existsSync(payerPath)) skip(`missing payer keypair at ${payerPath}`);
  const payer = Keypair.fromSecretKey(
    new Uint8Array(JSON.parse(fs.readFileSync(payerPath, "utf8"))),
  );

  // 4. Connection + payer funding check.
  const rpc = process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";
  const connection = new Connection(rpc, "confirmed");

  const payerBal = await connection.getBalance(payer.publicKey);
  if (payerBal < MIN_PAYER_LAMPORTS) {
    skip(
      `payer ${payer.publicKey.toBase58()} has ${payerBal / LAMPORTS_PER_SOL} SOL ` +
        `(< ${MIN_PAYER_LAMPORTS / LAMPORTS_PER_SOL})`,
    );
  }

  // 5. Anchor provider + vault program.
  const provider = new AnchorProvider(connection, new Wallet(payer), {
    commitment: "confirmed",
  });
  const vaultIdl = vaultIdlJson as unknown as Idl;
  const vaultProgramId = new PublicKey((vaultIdlJson as { address: string }).address);
  const program = new Program(vaultIdl, provider);

  // 6. Derive vault PDA + check initialization state.
  const [vaultPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), mintPk.toBuffer()],
    vaultProgramId,
  );

  // Fetch vault account if exists; otherwise initialize.
  let shareMint: PublicKey;
  const vaultAccountInfo = await connection.getAccountInfo(vaultPda);
  if (vaultAccountInfo) {
    const vaultAcc = (await (program.account as any).vault.fetch(vaultPda)) as {
      shareMint: PublicKey;
    };
    shareMint = vaultAcc.shareMint;
    console.log(`vault ${vaultPda.toBase58()} already initialized (shareMint=${shareMint.toBase58()})`);
  } else {
    console.log(`initializing vault for asset_mint=${mintPk.toBase58()}`);
    const shareMintKp = Keypair.generate();
    await (program.methods as any)
      .initializeVault()
      .accounts({
        vault: vaultPda,
        assetMint: mintPk,
        shareMint: shareMintKp.publicKey,
        payer: payer.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([shareMintKp])
      .rpc();
    shareMint = shareMintKp.publicKey;
    console.log(`vault initialized; shareMint=${shareMint.toBase58()}`);
  }

  // 7. Ensure vault_ata exists (owner = vault PDA, off-curve, payer = fee payer).
  const vaultAta = await ensureAtaForOwner(connection, payer, mintPk, vaultPda, true);

  // 8. Ensure depositor USDC ATA + share ATA exist, fee-paid by `payer` so the
  //    depositor wallet doesn't need SOL beyond what seed-usdc.ts already gave
  //    it (and so the harness works even if the depositor has 0 lamports).
  const depositorAta = await getOrCreateAssociatedTokenAccount(
    connection,
    payer,
    mintPk,
    depositor.publicKey,
  );
  const depositorShareAta = await getOrCreateAssociatedTokenAccount(
    connection,
    payer,
    shareMint,
    depositor.publicKey,
  );

  // Sanity: depositor must have >= 100 USDC.
  const depAtaAcc = await getAccount(connection, depositorAta.address);
  if (depAtaAcc.amount < BigInt(DEPOSIT_AMOUNT.toString())) {
    fail(
      `depositor ${depositor.publicKey.toBase58()} has ${depAtaAcc.amount} atoms of USDC; ` +
        `need ${DEPOSIT_AMOUNT.toString()}. Re-run seed-usdc.ts.`,
    );
  }

  // 9. Deposit.
  console.log(
    `deposit 100 USDC from ${depositor.publicKey.toBase58()} -> vault ${vaultPda.toBase58()}`,
  );
  const [vaultConfigPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault_config")],
    program.programId,
  );
  const existingCfg = await (program.account as any).vaultConfig.fetchNullable(
    vaultConfigPda,
  );
  if (!existingCfg) {
    // First-writer-wins init with Civic gate disabled (default pubkey).
    await (program.methods as any)
      .initializeVaultConfig(PublicKey.default)
      .accounts({
        vaultConfig: vaultConfigPda,
        admin: provider.wallet.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
  }

  const sig: string = await (program.methods as any)
    .deposit(DEPOSIT_AMOUNT)
    .accounts({
      vault: vaultPda,
      assetMint: mintPk,
      shareMint,
      vaultAta,
      depositorAta: depositorAta.address,
      depositorShareAta: depositorShareAta.address,
      depositor: depositor.publicKey,
      tokenProgram: TOKEN_PROGRAM_ID,
      vaultConfig: vaultConfigPda,
      gatewayToken: SystemProgram.programId,
    })
    .signers([depositor])
    .rpc();
  console.log(`deposit tx: ${sig}`);

  // Confirm on-chain as a belt-and-braces step before asking Supabase.
  await connection.confirmTransaction(sig, "confirmed");

  // 10. Poll Supabase for the `deposited` row with matching signature.
  const supabase: SupabaseClient = createClient(supabaseUrl, supabaseKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  type EventRow = { payload: any; event_name: string; signature: string };
  const deadline = Date.now() + POLL_TIMEOUT_MS;
  let row: EventRow | null = null;

  while (Date.now() < deadline) {
    const { data, error } = await supabase
      .from("onchain_events")
      .select("payload, event_name, signature")
      .eq("signature", sig)
      .eq("event_name", "deposited")
      .maybeSingle();
    if (error && error.code !== "PGRST116") {
      fail(`Supabase query error: ${error.message}`, error);
    }
    if (data) {
      row = data as unknown as EventRow;
      break;
    }
    await sleep(POLL_INTERVAL_MS);
  }

  if (!row) {
    fail(
      `no onchain_events row with event_name='deposited' and signature=${sig} ` +
        `within ${POLL_TIMEOUT_MS}ms. Is apps/indexer running against Devnet?`,
    );
  }

  // 11. Assertions on payload. Be tolerant of string or number BN encoding.
  const payload = row.payload ?? {};
  const amountStr = String(payload.amount);
  const sharesStr = String(
    payload.shares_minted ?? payload.sharesMinted,
  );
  if (amountStr !== DEPOSIT_AMOUNT.toString()) {
    fail(`payload.amount=${amountStr} expected ${DEPOSIT_AMOUNT.toString()}`);
  }
  // First deposit in a fresh vault mints 1:1. If the vault already had deposits
  // (shareMint reused across runs), shares_minted may differ. Only hard-assert
  // 1:1 when this run initialized the vault; otherwise just require non-zero.
  if (!vaultAccountInfo) {
    if (sharesStr !== DEPOSIT_AMOUNT.toString()) {
      fail(
        `first-deposit payload.shares_minted=${sharesStr} expected ` +
          `${DEPOSIT_AMOUNT.toString()} (1:1 on fresh vault)`,
      );
    }
  } else {
    if (!sharesStr || sharesStr === "0" || sharesStr === "undefined") {
      fail(`payload.shares_minted=${sharesStr} must be non-zero`);
    }
  }

  console.log(
    `OK: deposited event observed; sig=${sig} amount=${amountStr} shares_minted=${sharesStr}`,
  );
  process.exit(EXIT_OK);
}

main().catch((e) => {
  console.error(e);
  process.exit(EXIT_FAIL);
});
